sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5.1

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
  - secure: CstKyfe08gjpe96RAn0n1d64szo/3ixXIU9VsUPwy7yRSGq5NtF/LxecUDFLmjbModIdCZx7ZEQ5b1UqtGtX3MflRdau08fuQ6JHyq35McMYJoRq3YF/N/y5RSXmjzoPlUd8mnO1VY9SFFDI4tosLhsxh4MQLRnyTHIQDsfShM1ZwDHnCSPmlLtQ5LjhduAVXXTKpFZvHbQr2DKeKqJajicN5vBQI4A7x8JqUErK/c1WCx3xHdAA2pcM3NYCYtaR0v8O2+YutcPiBvnl8EMRGKaQP4SdX0tvMIoOLcTdDkfV4Of2OgvniL7Ua50XiMIpYHGNFtj1h9d+Q753UAh0G0SuhZXL7hyW0LHU324WuEGvzZuAEmO6Jg0QfnDOq9CR5c7XY3Oxz4DSIeB0lv3FbZ9qbnBSBoxIHUbsaxfrxem2zhb2wry0JDSAZyhIuefQ0f3aWWgKFcGpj4bLdwjhpCyF8n2s273pCrO2bXWkc4obwb+qyhdNnV1JAwYqkcxdBpsNYcZLnXg1TY/afexOLZfS7IjC0h5QCRdB/xG3VCBL43HrcjNuYb5F0RskQDQqV1QaWKaBw+vsOzRNgLo74/73icza+GI8hX6djpjD0UwSP3CiKvapizs7sN5CVrWg0hVMJw/2C9zG3MNyQD/W5N7WBlak8d2x3h+0KFmPFug=
branches:
  only:
  - master