sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5.1

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    - secure: S6CdNJtdmZo3iQ17EEeXSPzpXSSQyJ2KDKjamFeOSgO121YSiFPsjKLo31qCIflPT6iNQmpFO1QTHoNlH5ucVuu0xBvzc6KMs5ZYJ5fKv9J2uPxQvcXrzJJgKKujGzFMc4rli0BCSrzkiyAQeHAWi4f4LXb0S5/0sMm5umhR0it+hRRTm/qMYQwlIMbJSlJ/KQ7TzacPddXT1VHwn6jD+7HIFRu8geh1z8TRJgRautW+h4G9fCxYD/x43mLEb4r/286HASFJBW4+TaTWhAD/gH/ojLdsZ6h+YP9P4rGtiFYCiOwEex+IJ6ZZIboXBEoFuDR1ORhMJ/xo7PGQZy9vuXYKEZAvhOCJiopv3aQFRIxLlvLiXUsvbOiHSvSFJZMYo8rkzXvluSd/i3704BKQNZ6USgvBeqWYEZmOymcWDMsFlGT9hHShNfSlCSugUNC0h5bCJZS/7ezplWWyTIiFfggXi+WrcxvtAdW9boD4D1J9Q1/4BQiilvs+jtRqJTY3AzFyZoyuBqZK9FJYvcjqa1/HCIEQFYRV0Gf0lUpxH1Oi1MZhY+/BrAqJ34QuS77XMSqA4qWGvRr/yUjKv/epaLw6l5k6e5egiQqZUgZ3YDtvTNsTq+pxJAocSID4ch6p/24CHUFJddBQWQZaUKyH73XZ0UE8gQj8RE2BxJbaY5Y=
branches:
  only:
  - master